# Site settings
title: Notes personnelles de Goligo
#email: 
description: > # this means to ignore newlines until "baseurl:"
    Site personnel me servant de pense-bête en ligne à propos de mes bidouillages électroniques et informatques sur Linux (surtout Archlinux), ROS, Raspberry Pi, Odroid, Arduino, dsPIC, ARM...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://romainreignier.github.io" # the base hostname & protocol for your site
twitter_username: goligo50
github_username:  romainreignier

# Build settings
markdown: kramdown
